<?php
/**-----------------------------------------------------------------------------
 * Database singleton class.
 * This class should be used when accessing database in object's model.
 *
 *                                ~ ~ ~ ~
 *                THE VARIABLE $dbconfig MUST BE MODIFIED
 *                      TO WORK IN ANOTHER SERVER
 *                                ~ ~ ~ ~
 *
 * More reading materials for transaction and even better sql handling:
 * http://forum.codecall.net/topic/44392-php-5-mysqli-prepared-statements/#axzz2CAUU8CJP
 * http://stackoverflow.com/questions/4381644/capture-error-and-continue-when-inserting-into-a-unique-column
 * -----------------------------------------------------------------------------
 */

define("ALL", "*");
define("ENCRYPTION_TYPE", "sha256");

class Database
{

	/**-------------------------------------------------------------------------
	 * Database configuration variables.
	 * Replace with appropriate database information during deployment or
	 * during testing.
	 * -------------------------------------------------------------------------
	 */
	private static $dbconfig = array
	(
		'host' 	=> 'localhost',
		'user' 	=> 'root',
		'pass' 	=> 'root',
		'database' => 'comp353'
	);

    // Turn on sql debugging. Sql error will be printed in html.
    private $debug = 1;


	/**-------------------------------------------------------------------------
	 * END OF DATABASE CONFIGURATION
     * -------------------------------------------------------------------------
	 */
	private static $dbInstance;

    private $sql;
    private $mysqli_result;

	private function __construct()
    {
        $this->mysqli = new mysqli
        (
            self::$dbconfig['host'],
            self::$dbconfig['user'],
            self::$dbconfig['pass'],
            self::$dbconfig['database']
        );

        if (mysqli_connect_errno())
        {
            printf("<p>Database connection failed: %s</p>", mysqli_connect_error());
            exit;
        }
    }

    /**
     * Singleton pattern.
     *
     * @return Database
     */
    public static function getInstance()
	{
		if (!isset(self::$dbInstance))
			self::$dbInstance = new Database;

		return self::$dbInstance;
	}

    /**
     * Return mysqli instance in case we really need to do some fancy stuffs.
     * @return Database|mysqli
     */
    public function getMysqliInstance()
    {
        return isset($this->mysqli) ?
            $this->mysqli : self::getInstance()->mysqli;
    }

    /**
     * Execute the sql statement. The statement is escaped.
     *
     * @param $sql
     * @return bool|mysqli_result
     */
    public function query($sql)
    {
        $this->sql = $this->mysqli->real_escape_string($sql);
        $this->mysqli_result = $this->mysqli->query($sql);

        if (!$this->mysqli_result && $this->debug)
        {
            printf("<p>Error(%d): %s. The problem is caused by this query: %s</p>"
                . "<p>This error message is generated by 'database.php'.</p>",
                $this->mysqli->errno, $this->mysqli->error, $this->sql);
        }

        return $this->mysqli_result;
    }

    /**
     * A helper method to get the data from sql result. Similar to a database
     * query of "SELECT $select" from a bunch of result in the form of an
     * array.
     *
     * Usage:
     *
     * $db->query($statement);
     * $db->get();
     *
     * @param int $fetchMode
     * @return array
     */
    public function fetch($fetchMode = MYSQL_ASSOC)
    {
        $data = array();

        while ($row = $this->mysqli_result->fetch_array($fetchMode))
            $data[] = $row;

        return $data;
    }

    /**
     * Return table attributes information of the result.
     *
     * @return mixed
     *
     */
    public function fetchFields()
    {
        return $this->mysqli_result->fetch_fields();
    }

    /**
     * Clean the memory of the resulting sql command results.
     */
    public function free()
    {
        $this->mysqli_result->free();
    }

    public function numberOfRows()
    {
        return isset($this->mysqli_result) ?
            $this->mysqli_result->num_rows : FALSE;
    }

    /**
     * Get the id of the last inserted query from "INSERT INTO...".
     * @return mixed
     */
    public function getLastInsertId()
    {
        return $this->mysqli->insert_id;
    }

    /**
     * Return mysqli error if there is any.
     * @return string
     */
    public function getErrorString()
    {
        return isset($this->mysqli->error) ? $this->mysqli->error : "" ;
    }

    /**
     * Return mysqli errno if there is any.
     * @return int
     */
    public function getErrorId()
    {
        return isset($this->mysqli->errno) ? $this->mysqli->errno : 0;
    }

    public function __destruct()
    {
        $this->mysqli->close();
    }

}
